config/routes.rb
PjaxExample::Application.routes.draw do
  controller :pages do
    get :welcome
    get :contact
    get :privacy
    get :terms
    get :about
  end

  resources :products

  root :to => 'pages#welcome'
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :title, :price, :quantity, :presence => true
  validates :price, :quantity, :numericality => true
  validates_numericality_of :quantity, :only_integer => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /welcome
  def welcome
  end

  # GET /contact
  def contact
  end

  # GET /privacy
  def privacy
  end

  # GET /terms
  def terms
  end

  # GET /about
  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    load_index()
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    render_after_save('new')
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])
    @product.attributes = params[:product]
    render_after_save('edit')
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    params.delete(:id)
    load_index()
  end

  private
  def render_after_save(action_on_error)
    if @product.save
      load_index()
    else
      render action: action_on_error
    end
  end

  def load_index
    @products = Product.all
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_head.html.haml
%meta{:charset => "utf-8"}
%meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
%meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
%meta{:content => "", :name => "description"}
%meta{:content => "", :name => "author"}

%title= content_for?(:title) ? yield(:title) : "PJAX Example"
= csrf_meta_tags

/ Le HTML5 shim, for IE6-8 support of HTML elements
/[if lt IE 9]
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
/ Le styles
= stylesheet_link_tag "application", :media => "all"

:css
  body {
    padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
  }

= javascript_include_tag "application"
= yield :javascript

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    = render "layouts/head"
    = yield(:head)

  %body
    = render "shared/nav"

    .container.content-container{ :'data-pjax-container' => true }
      = render "shared/flash_messages"
      = yield

    = render 'shared/footer'

app/views/pages/about.html.haml
%h1 About

app/views/pages/contact.html.haml
%h1 Contact

app/views/pages/privacy.html.haml
%h1 Privacy

app/views/pages/terms.html.haml
%h1 Terms and Conditions

app/views/pages/welcome.html.haml
%h1 Welcome!

app/views/products/_form.html.haml
= form_for @product, :html => { :method => submit_method } do |f|
  - if @product.errors.any?
    #error_explanation
      %h2
        = pluralize(@product.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .control-group
    = f.label :price, :class => 'control-label'
    .controls
      = f.text_field :price, :class => 'text_field'
  .control-group
    = f.label :quantity, :class => 'control-label'
    .controls
      = f.number_field :quantity, :class => 'number_field'
  .control-group
    = f.label :published, :class => 'control-label'
    .controls
      = f.check_box :published, :class => 'check_box'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), |
      products_path, :class => 'btn'                               |

app/views/products/edit.html.haml
- model_class = Product
.page-header
  %h1= t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, |
      :default => "Edit #{model_class.model_name.human}")                                      |

= render :partial => 'form', :locals => {:submit_method => :put}

app/views/products/index.html.haml
- model_class = Product

= link_to t('.new', :default => t("helpers.links.new")), new_product_path, :class => 'btn btn-primary pull-right'

.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize

- if @products.any?
  %table.table.table-striped
    %thead
      %tr
        %th= model_class.human_attribute_name(:id)
        %th= model_class.human_attribute_name(:title)
        %th= model_class.human_attribute_name(:description)
        %th= model_class.human_attribute_name(:price)
        %th.center= model_class.human_attribute_name(:quantity)
        %th.center= model_class.human_attribute_name(:published)
        %th.datetime= model_class.human_attribute_name(:created_at)
        %th.actions= t '.actions', :default => t("helpers.actions")
    %tbody
      - @products.each do |product|
        %tr
          %td= link_to product.id, product_path(product)
          %td= product.title
          %td= product.description
          %td= product.price
          %td.center= product.quantity
          %td.center= product.published
          %td.datetime= l product.created_at
          %td.actions
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(product), :class => 'btn btn-mini'
            = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
              product_path(product),  :method => :delete, :class => 'btn btn-mini btn-danger',                                                                  |
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure, you want to delete the product?')) } |

- else
  .empty No product found.

app/views/products/new.html.haml
- model_class = Product

.page-header
  %h1
    = t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
    :default => "New #{model_class.model_name.human}")

= render :partial => 'form', :locals => {:submit_method => :post}

app/views/products/show.html.haml
- model_class = Product

.page-header
  %h1= t '.title', :default => model_class.model_name.human

%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:title)
      \:
  %dd= @product.title
  %dt
    %strong
      = model_class.human_attribute_name(:description)
      \:
  %dd= @product.description
  %dt
    %strong
      = model_class.human_attribute_name(:price)
      \:
  %dd= @product.price
  %dt
    %strong
      = model_class.human_attribute_name(:quantity)
      \:
  %dd= @product.quantity
  %dt
    %strong
      = model_class.human_attribute_name(:published)
      \:
  %dd= @product.published

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), products_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(@product), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
    product_path(@product), :method => 'delete', :class => 'btn btn-danger',                                                                                         |
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } |

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  %div{:class => "alert alert-#{{:notice => :info, :alert => :error}[type] || type}"}
    %a.close{:"data-dismiss" => "alert"}
      &times;
    = message

app/views/shared/_footer.html.haml
.footer
  .container
    #footer-line
      .pull-left
        = link_to 'Home', root_path
        |
        = link_to 'About', about_path
        |
        = link_to 'Contact', contact_path
        |
        = link_to 'Privacy', privacy_path
        |
        = link_to 'Terms', terms_path

      .pull-right
        Copyright © #{Date.today.year}

app/views/shared/_nav.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "PJAX Example", root_path, {:class => 'brand'}

      .container.nav-collapse
        %ul.nav.pull-right
          %li.dropdown
            %a.dropdown-toggle{:href => "javascript:void(0);", "data-toggle" => "dropdown"}
              Products
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Add New", new_product_path
              %li= link_to "View All", products_path